config/routes.rb
DoxsiteApiTest::Application.routes.draw do

  post "/digital_objects/filter_by"
  resources :digital_objects
  
  resources :emails do
    member do
      post "add_tag"
      post "untag"
    end
  end

  resources :user_doxsites

  resources :file_assets do
    member do
      post "add_tag"
      post "add_tag_by_name"
      post "untag"
    end
  end

  get "tags/new"
  get "tags/all"
  post "tags/destroy"
  match "/tags/new" => "tags#add"
    
  resources :oauth_consumers do
    member do
      get :callback
      get :callback2
      match 'client/*endpoint' => 'oauth_consumers#client'
    end
  end

  get "welcome/index"
  get "welcome/file_assets"
  
  devise_for :users

  root :to => "welcome#index"

end

app/controllers/welcome_controller.rb
require 'rubygems'
require 'oauth'

class WelcomeController < ApplicationController
  include ApplicationHelper

 
   
  def index
    #    puts " start " * 10
    #    @file =File.open('/test/text_sample.txt')
    #    puts access_token.delete('/api/v1/tags/name/png')
    @users = User.all
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/file_assets.html.erb
<h2>All personal file assets </h2>
<%= render "general/info_no_parsing" %>
<% if access_token %>
  <%= access_token.get("/api/v1/file_assets").body %>
<% else %>
  <%= render "general/info_oauth" %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome</h1>
<h4>This is one basic application to test the Doxsite-API, using the OAuth service.</h4>
<b>Users</b> (you must create a new account in order to continue):
<ol>
  <% @users.each do |u| %>
    <li><%= u.email %></li>
  <% end %>
</ol>
<p>
  If you are already connected to Doxsite (through API: click <%= link_to 'here', oauth_consumers_path %> to see the current status) you can:
</p>
<hr/>

<p>

</p>
<table class="api_test">
  <tr>
    <th>Object</th>
    <th>Methods</th>
    <th>Note</th>
  </tr>

  <tr>
    <td>Tags</td>
    <td align="right">
      See <%= link_to "All Tags", tags_all_path %>
      <br/>
      Create <%= link_to "New Tags", tags_new_path %>
      <br/>
    </td>
    <td>you can also delete delete tags</td>
  </tr>
  <tr>
    <td>File Assets</td>
    <td align="right">
      See <%= link_to "All File Assets", file_assets_path %>
      <br/>
      Create <%= link_to "New File Assets", new_file_asset_path %>
      <br/>
    </td>
    <td>add tags, untag, delete file asset</td>
  </tr>
  <tr>
    <td>Digital Objects</td>
    <td align="right">
      See <%= link_to "My Digital Object", digital_objects_path %>
    </td>
  </tr>
  <tr>
    <td>Users</td>
    <td align="right">
      Create <%= link_to "New User", new_user_doxsite_path %>
    </td>
  </tr>
  <tr>
    <td>Emails</td>
    <td align="right">
      See <%= link_to "my emails", emails_path %>
    </td>
    <td>add tags, untag, delete emails, show attachments, html and text body, other details</td>
  </tr>
</table>
<hr/>
<p><b>Note:</b> On this pages you will see the details of some objects displayed in <a href="http://en.wikipedia.org/wiki/JSON">JSON</a> format(the default format returned by our DOXSITE-API)</p>