config/routes.rb
DoxsiteApiTest::Application.routes.draw do

  post "/digital_objects/filter_by"
  resources :digital_objects
  
  resources :emails do
    member do
      post "add_tag"
      post "untag"
    end
  end

  resources :user_doxsites

  resources :file_assets do
    member do
      post "add_tag"
      post "add_tag_by_name"
      post "untag"
    end
  end

  get "tags/new"
  get "tags/all"
  post "tags/destroy"
  match "/tags/new" => "tags#add"
    
  resources :oauth_consumers do
    member do
      get :callback
      get :callback2
      match 'client/*endpoint' => 'oauth_consumers#client'
    end
  end

  get "welcome/index"
  get "welcome/file_assets"
  
  devise_for :users

  root :to => "welcome#index"

end

app/models/user_doxsite.rb
class UserDoxsite
end

app/controllers/user_doxsites_controller.rb
require 'json'

class UserDoxsitesController < ApplicationController
  include ApplicationHelper

  #before_filter :authenticate_user!

  respond_to  :html

  # GET /user_doxsites
  # GET /user_doxsites.xml
  def index
  end

  # GET /user_doxsites/1
  # GET /user_doxsites/1.xml
  def show
  end

  # GET /user_doxsites/new
  # GET /user_doxsites/new.xml
  def new
  end

  # GET /user_doxsites/1/edit
  def edit
  end

  # POST /user_doxsites
  # POST /user_doxsites.xml
  def create
    result = access_token.post('/api/v1/users/create', {:email=>params[:email],:psw=>params[:password],:psw_conf=>params[:password_conf],:inbox=>params[:inbox]})
    display_api_response result
    respond_with("",:location => :back)
  end

  # PUT /user_doxsites/1
  # PUT /user_doxsites/1.xml
  def update
  end

  # DELETE /user_doxsites/1
  # DELETE /user_doxsites/1.xml
  def destroy
  end
end

app/helpers/user_doxsites_helper.rb
module UserDoxsitesHelper
end

app/views/user_doxsites/_form.html.erb
<%= form_tag('/user_doxsites') do %>
  <div class="field">
    <table>
      <tr>
        <th></th>
        <th></th>
      </tr>
      <tr>
        <td><%= label_tag "user inbox:" %></td>
        <td><%= text_field_tag(:inbox) %></td>
      </tr>
      <tr>
        <td><%= label_tag "email" %></td>
        <td> <%= text_field_tag(:email) %></td>
      </tr>
      <tr>
        <td><%= label_tag "password" %></td>
        <td><%= password_field_tag(:password) %></td>
      </tr>
      <tr>
        <td><%= label_tag "password confirmation" %></td>
        <td><%= password_field_tag(:password_conf) %></td>
      </tr>
    </table>
  </div>
  <div class="actions">
    <%= submit_tag("Create new user")%>
  </div>
<% end %>

app/views/user_doxsites/edit.html.erb
<h1>Editing user_doxsite</h1>

<%= render 'form' %>
<%= link_to 'Back', user_doxsites_path %>

app/views/user_doxsites/index.html.erb
<h1>Listing user_doxsites</h1>
<br />

<%= link_to 'New User doxsite', new_user_doxsite_path %>

app/views/user_doxsites/new.html.erb
<h1>New Doxsite user</h1>

<%= render 'form' %>

<%= link_to 'Back', user_doxsites_path %>

app/views/user_doxsites/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_user_doxsite_path(@user_doxsite) %> |
<%= link_to 'Back', user_doxsites_path %>