config/routes.rb
DoxsiteApiTest::Application.routes.draw do

  post "/digital_objects/filter_by"
  resources :digital_objects
  
  resources :emails do
    member do
      post "add_tag"
      post "untag"
    end
  end

  resources :user_doxsites

  resources :file_assets do
    member do
      post "add_tag"
      post "add_tag_by_name"
      post "untag"
    end
  end

  get "tags/new"
  get "tags/all"
  post "tags/destroy"
  match "/tags/new" => "tags#add"
    
  resources :oauth_consumers do
    member do
      get :callback
      get :callback2
      match 'client/*endpoint' => 'oauth_consumers#client'
    end
  end

  get "welcome/index"
  get "welcome/file_assets"
  
  devise_for :users

  root :to => "welcome#index"

end

app/controllers/file_assets_controller.rb
require 'rubygems'
require 'json'
require 'rest_client'

class FileAssetsController < ApplicationController
  include ApplicationHelper
  respond_to  :html

  before_filter :authenticate_user!
  
  # GET /file_assets
  # GET /file_assets.xml
  def index
    @file_assets = JSON[access_token.get("/api/v1/file_assets").body]
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @file_assets }
    end
  end

  # GET /file_assets/1
  # GET /file_assets/1.xml
  def show
    @fa_id=setup_id
    @file_asset = JSON(access_token.get("/api/v1/file_assets/#{@fa_id}").body)
    @tags_obj = JSON[access_token.get("/api/v1/tags").body]
    @file_asset_tags = JSON[access_token.get("/api/v1/file_assets/#{@fa_id}/tags").body]
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @file_asset }
    end
  end

  # GET /file_assets/new
  # GET /file_assets/new.xml
  def new
  end

  # GET /file_assets/1/edit
  def edit
    #@file_asset = FileAsset.find(params[:id])
  end

  # POST /file_assets
  # POST /file_assets.xml
  def create
    # this post requires authentication so i send the current access_token
    RestClient.add_before_execution_proc do |req, params|
      access_token.sign! req
    end
    RestClient.post "http://#{Rails.my.www_domain}/api/v1/file_assets/create", :file_asset =>params["file"]
    #with access token doesn't work
    #@file_asset = access_token.post('/api/v1/file_assets/create', {:file_asset=>params["file"]})
    flash[:notice] = "Operation terminated. Check if the file is uploaded on Doxsite (testing)"
    respond_with("",:location => file_assets_path)
  end

  # PUT /file_assets/1
  # PUT /file_assets/1.xml
  def update
  end

  # DELETE /file_assets/1
  # DELETE /file_assets/1.xml
  def destroy
    puts "delete --" * 10
    result = access_token.delete("/api/v1/file_assets/#{params[:id]}")

    display_api_response( result )
    
    respond_to do |format|
      format.html { redirect_to(file_assets_url) }
      format.xml  { head :ok }
    end
  end

  def add_tag
    result = access_token.post("/api/v1/file_assets/#{setup_id}/tags/#{setup_tag_id}")
    display_api_response result
    respond_with("",:location => :back)
  end

  def add_tag_by_name
    result = access_token.post("/api/v1/file_assets/#{setup_id}/tags", {:name=>params[:tag_name]})
    display_api_response result
    respond_with("",:location => :back)
  end



  def untag
    result = access_token.delete("/api/v1/file_assets/#{setup_id}/tags/#{params[:tag_id]}")
    display_api_response( result )
    respond_with("",:location => :back)
  end

  private

  def setup_id
    params[:id]
  end

  def setup_file
    params[:file]
  end
    
  def setup_tag_id
    params[:tag][:tag_id].sub("-",":")
  end

end

app/helpers/file_assets_helper.rb
module FileAssetsHelper
end

app/views/file_assets/_form.html.erb
<%= form_tag('/file_assets',:multipart => true,:method => :create)  do %>
  <div class="field">
    <%= label_tag "file".to_sym, "Select file:" %>
    <%= file_field_tag "file".to_sym %>
  </div>
  <div class="actions">
    <%= submit_tag("Add file asset")%>
  </div>
<% end %>

app/views/file_assets/edit.html.erb
<h1>Editing file_asset</h1>

<%= render 'form' %>

<%= link_to 'Show', @file_asset %> |
<%= link_to 'Back', file_assets_path %>

app/views/file_assets/index.html.erb
<h1>Listing All File Assets</h1>

<p>Testing the GET method of the API.</p>
<p>In this table you will see the id's of all file assets from dev.doxsite.com. You can also test the GET/DELETE method on one individual file asset clicking SHOW or the DELETE links.</p>
<p>You can also the the POST create method using the New File asset link.</p>
<%= link_to 'New File asset', new_file_asset_path %>
<hr/>
<br />

<table class="listing">
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Size</th>
    <th>Type</th>
    <th>Note</th>
  </tr>
  <br/>
  IDs found: <b><%= @file_assets.keys.count %> </b>
  <% @file_assets.each do |key,value| %>
    <tr>
      <td><%= key %></td>
      <td><%= value["name"]%></td>
      <td><%= value["size"]%></td>
      <td><%= value["type"]%></td>
      <td><%= value["note"]%></td>
      <td><%= link_to 'Show', file_asset_path(key.sub("-",":")) %></td>
      <td><%= link_to 'Delete', file_asset_path(key.sub("-",":")), :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

app/views/file_assets/new.html.erb
<h1>Upload your asset to Doxsite</h1>

<%= render 'form' %>

<%= link_to 'Back', file_assets_path %>

app/views/file_assets/show.html.erb
<h2>File asset details</h2>
<p>
  This page test the following API methods:
<li>GET information about current file asset</li>
<li>GET all tags of this file asset</li>
<li>GET all tags available</li>
<li>DELETE remove(untagging) tags from this file asset</li>
<li>POST tagging this file asset using one available tag </li>
</p>
<hr/>
<h5>File asset tags</h5>
<ol>
  <% @file_asset_tags.each do |tag| %>
    <li>
      <%= tag[0] %>
      <%= link_to "untag", untag_file_asset_path(@fa_id,:tag_id=>tag[0].sub("-",":")), :method =>:post %>
    </li>
  <% end %>
</ol>
<h5>Tag this file asset</h5>
<p>(the id is displayed in this list for testing purpose - the developer can also display the name of the tag, or any other information returned by GET method) </p>
<%= render "tags/tag_object", :controller=>"file_assets" %>

<h5>Tag using tag name</h5>
<%= render "tags/tag_object_by_name", :controller=>"file_assets" %>

<%= link_to 'Back', file_assets_path %>