config/routes.rb
DoxsiteApiTest::Application.routes.draw do

  post "/digital_objects/filter_by"
  resources :digital_objects
  
  resources :emails do
    member do
      post "add_tag"
      post "untag"
    end
  end

  resources :user_doxsites

  resources :file_assets do
    member do
      post "add_tag"
      post "add_tag_by_name"
      post "untag"
    end
  end

  get "tags/new"
  get "tags/all"
  post "tags/destroy"
  match "/tags/new" => "tags#add"
    
  resources :oauth_consumers do
    member do
      get :callback
      get :callback2
      match 'client/*endpoint' => 'oauth_consumers#client'
    end
  end

  get "welcome/index"
  get "welcome/file_assets"
  
  devise_for :users

  root :to => "welcome#index"

end

app/models/digital_object.rb
class DigitalObject < ActiveRecord::Base
end

app/controllers/digital_objects_controller.rb
require 'json'

class DigitalObjectsController < ApplicationController
  include ApplicationHelper
  before_filter :authenticate_user!
  respond_to  :html

  
  # GET /digital_objects
  # GET /digital_objects.xml
  def index
    puts params.inspect
    @digital_objects = JSON[access_token.get("/api/v1/digital_objects/my").body]
    @tags_obj = JSON[access_token.get("/api/v1/tags").body]
    @contacts = JSON[access_token.get("/api/v1/contacts").body]
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @digital_objects }
    end
  end

  # GET /digital_objects/1
  # GET /digital_objects/1.xml
  def show
    @digital_object = DigitalObject.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @digital_object }
    end
  end

  # GET /digital_objects/new
  # GET /digital_objects/new.xml
  def new
    @digital_object = DigitalObject.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @digital_object }
    end
  end

  # GET /digital_objects/1/edit
  def edit
    @digital_object = DigitalObject.find(params[:id])
  end

  # POST /digital_objects
  # POST /digital_objects.xml
  def create
    @digital_object = DigitalObject.new(params[:digital_object])

    respond_to do |format|
      if @digital_object.save
        format.html { redirect_to(@digital_object, :notice => 'Digital object was successfully created.') }
        format.xml  { render :xml => @digital_object, :status => :created, :location => @digital_object }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @digital_object.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /digital_objects/1
  # PUT /digital_objects/1.xml
  def update
    @digital_object = DigitalObject.find(params[:id])

    respond_to do |format|
      if @digital_object.update_attributes(params[:digital_object])
        format.html { redirect_to(@digital_object, :notice => 'Digital object was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @digital_object.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /digital_objects/1
  # DELETE /digital_objects/1.xml
  def destroy
    @digital_object = DigitalObject.find(params[:id])
    @digital_object.destroy

    respond_to do |format|
      format.html { redirect_to(digital_objects_url) }
      format.xml  { head :ok }
    end
  end


  def filter_by
    all_filters ={}
    all_filters["tags"] = params[:tags_id] if params[:tags_id]
    all_filters["contacts"] = params[:contacts_id] if params[:contacts_id]
    all_filters.each_value { |value| value.collect { |item| item.sub!("-",":") }  }
    @digital_object_filtered =  JSON[access_token.post("/api/v1/digital_objects/my",all_filters).body]
    puts "--" * 10
  end
  
end

app/helpers/digital_objects_helper.rb
module DigitalObjectsHelper
end

app/views/digital_objects/_all.html.erb
<p>ID's found: <b><%= digital_objects.keys.count-1 %></b> </p>
<table class="listing">
  <tr>
    <th>ID</th>
    <th>Other details of the object</th>
  </tr>

  <% digital_objects.each do |key,value| %>
    <tr>
      <td><%= key %></td>
      <td><%= value%></td>
    </tr>
  <% end %>
</table>
<br />

app/views/digital_objects/_form.html.erb
<%= form_for(@digital_object) do |f| %>
  <% if @digital_object.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@digital_object.errors.count, "error") %> prohibited this digital_object from being saved:</h2>

      <ul>
      <% @digital_object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/digital_objects/edit.html.erb
<h1>Editing digital_object</h1>

<%= render 'form' %>

<%= link_to 'Show', @digital_object %> |
<%= link_to 'Back', digital_objects_path %>

app/views/digital_objects/filter_by.html.erb
<h1>Listing filtered digital_objects</h1>
<%= link_to "Back", digital_objects_path %>
<%= render "all", :digital_objects=>@digital_object_filtered%>

app/views/digital_objects/index.html.erb
<h1>Listing my digital_objects</h1>
<p>Testing the GET method of the API.</p>
<p>In this table you will see the id of all personal digital objects from dev.doxsite.com. You can also test the GET/DELETE method on one individual file asset clicking SHOW or the DELETE links.</p>
<p>You can also add a <%= link_to 'new digital object', new_file_asset_path %> (file asset)</p>
<br/>

<%= render "filter/form" %>

<%= render "all",:digital_objects=>@digital_objects %>

<%= link_to 'New Digital object', new_file_asset_path %>

app/views/digital_objects/new.html.erb
<h1>New digital_object</h1>

<%= render 'form' %>

<%= link_to 'Back', digital_objects_path %>

app/views/digital_objects/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_digital_object_path(@digital_object) %> |
<%= link_to 'Back', digital_objects_path %>